config/routes.rb
Rails.application.routes.draw do
  root to: "characters#index"

  # shadow rodauth routes for js-from-routes generator
  defaults export: true do
    controller :rodauth do
      post "change-password", action: :change_password
      post "create-account", action: :create_account
      post "login", action: :login
      post "logout", action: :logout
      post "reset-password", action: :reset_password
      post "reset-password-request", action: :reset_password_request
      post "verify-account", action: :verify_account
    end
  end

  namespace :admin do
    root to: "accounts#index"
    resources :accounts
  end

  resources :characters, export: true

  get "search", to: "characters#search", as: :search
  get "search/:q", to: "characters#search", export: true
end

app/models/account.rb
class Account < ApplicationRecord
  include Rodauth::Rails.model
  enum :status, unverified: 1, verified: 2, closed: 3
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  has_rich_text :description
  has_rich_text :notes

  validates :player, presence: true

  ThinkingSphinx::Callbacks.append(
    self, behaviours: [:real_time]
  )

  def description_plain_text
    description.body&.to_plain_text
  end

  def notes_plain_text
    notes.body&.to_plain_text
  end
end

app/controllers/admin/accounts_controller.rb
module Admin
  class AccountsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def update
      if requested_resource == current_account && (resource_params[:status] != "verified" || resource_params[:admin] != "1")
        flash[:error] = "Please don't break your own account."
        redirect_to({ action: :index })
      else
        super
      end
    end

    def destroy
      if requested_resource == current_account
        flash[:error] = "Please don't delete your own account."
        redirect_to({ action: :index })
      else
        super
      end
    end

    def default_sorting_attribute
      :email
    end

    def default_sorting_direction
      :asc
    end
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :require_admin

    private

    def require_admin
      rodauth.require_account
      redirect_back_or_to(root_path, alert: "Only admins can access Dashboards.") unless current_account.admin?
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :require_account, only: [:new, :edit, :update, :destroy]
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html do
        # @characters = Character.page params[:page]
        render layout: "vue", action: :vue
      end

      format.json do
        @characters = Character.all
        render :index
      end
    end
  end

  def show; end

  def new
    @character = Character.new
  end

  def edit; end

  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully added.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:q].present?
      respond_to do |format|
        format.html do
          render layout: "vue", action: :vue
        end

        format.json do
          @characters = Character.search params[:q],
                                         per_page: Character.count,
                                         max_matches: Character.count

          render :index
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to root_url }
        format.json { render status: :unprocessable_entity }
      end
    end
  end

  private

  def require_account
    rodauth.require_account
  end

  def set_character
    @character = Character.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def character_params
    params.require(:character).permit(:mortal_name, :fae_name, :rank, :kith,
                                      :location, :position, :player,
                                      :seeming, :house, :bannerhouse,
                                      :description, :notes)
  end
end

app/controllers/rodauth_controller.rb
class RodauthController < ApplicationController
  # used by Rodauth for rendering views, CSRF protection, and running any
  # registered action callbacks and rescue_from handlers
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
  def options_for_datalist(field)
    Character.group(field).
              order(field).
              pluck(field).
              filter { |f| f.present? }
  end
end

app/helpers/mailer_helper.rb
module MailerHelper
  def url_from_path(path)
    path = "/#{path}" unless path.start_with?("/")

    URI::HTTP.build(
      Rails.application.config.action_mailer.default_url_options.merge({ path: path } )
    ).to_s
  end
end

app/views/active_storage/blobs/_blob.html.haml
%figure{:class => "attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}"}
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/admin/application/_flashes.html.haml
- if flash.any?
  .flashes
    - flash.each do |key, value|
      - next unless value.respond_to?(:html_safe)
      %div{:class => "flash flash-#{key}"}= value.html_safe

app/views/admin/application/_icons.html.haml
%svg{:hidden => "", :xmlns => "http://www.w3.org/2000/svg"}
  %symbol#icon-cancel{:viewbox => "0 0 48 48"}
    %path{:d => "M24 19.757l-8.485-8.485c-.784-.783-2.047-.782-2.827 0l-1.417 1.416c-.777.777-.78 2.046.002 2.827L19.757 24l-8.485 8.485c-.783.784-.782 2.047 0 2.827l1.416 1.417c.777.777 2.046.78 2.827-.002L24 28.243l8.485 8.485c.784.783 2.047.782 2.827 0l1.417-1.416c.777-.777.78-2.046-.002-2.827L28.243 24l8.485-8.485c.783-.784.782-2.047 0-2.827l-1.416-1.417c-.777-.777-2.046-.78-2.827.002L24 19.757zM24 47c12.703 0 23-10.297 23-23S36.703 1 24 1 1 11.297 1 24s10.297 23 23 23z", "fill-rule" => "evenodd"}
  %symbol#icon-eyeglass{:viewbox => "0 0 48 48"}
    %path{:d => "M27.885 32.515c-2.864 1.966-6.333 3.116-10.07 3.116C7.976 35.63 0 27.656 0 17.817 0 7.976 7.976 0 17.816 0S35.63 7.976 35.63 17.816c0 3.736-1.15 7.205-3.115 10.07l14.53 14.53c1.278 1.277 1.275 3.352 0 4.628-1.28 1.278-3.353 1.278-4.63 0l-14.53-14.53zm-10.07-3.736c6.056 0 10.964-4.91 10.964-10.964 0-6.055-4.91-10.964-10.964-10.964-6.055 0-10.964 4.91-10.964 10.964 0 6.055 4.91 10.963 10.964 10.963z"}
  %symbol#icon-up-caret{:viewbox => "0 0 48 48"}
    %path{:d => "M2.988 33.02c-1.66 0-1.943-.81-.618-1.824l20-15.28c.878-.672 2.31-.67 3.188 0l20.075 15.288c1.316 1.003 1.048 1.816-.62 1.816H2.987z"}

app/views/admin/application/_javascript.html.haml
- Administrate::Engine.javascripts.each do |js_path|
  = javascript_include_tag js_path
= yield :javascript
- if Rails.env.test?
  = javascript_tag do
    $.fx.off = true;
    $.ajaxSetup({ async: false });

app/views/admin/application/_navigation.html.haml
%nav.navigation{:role => "navigation"}
  = link_to(t("administrate.navigation.back_to_app"), root_url, class: "button button--alt button--nav") if defined?(root_url)
  - Administrate::Namespace.new(namespace).resources_with_index_route.each do |resource|
    - if valid_action?(:index, resource) && show_action?(:index, model_from_resource(resource))
      = link_to(display_resource_name(resource), resource_index_route(resource),
          class: "navigation__link navigation__link--#{nav_link_state(resource)}")

  -# = button_to "Sign out", sign_out_path, { method: :delete, data: { confirm: "Are you sure?" },
  -#     class: 'button button--alt button--nav', style: 'margin-top: 1.5em' }

app/views/admin/application/_stylesheet.html.haml
- Administrate::Engine.stylesheets.each do |css_path|
  = stylesheet_link_tag css_path
= yield :stylesheet

app/views/characters/_form.html.haml
= form_for @character, { html: { autocomplete: "off" } } do |f|
  - if @character.errors.any?
    %div.alert.alert-error.mb-6#error_explanation
      = "#{pluralize(@character.errors.count, 'error')} prohibited this character from being saved:"
      %ul.mb-0
        - @character.errors.full_messages.each do |message|
          %li= message

  .form-control
    = f.label :player, class: "label label-text text-secondary"
    = f.text_field :player, list: "player", class: "input input-sm input-bordered"
    %datalist#player
      = options_for_select(options_for_datalist(:player))

  - %i[fae_name mortal_name].each do |field|
    .form-control
      = f.label field, field.to_s.titlecase, class: "label label-text text-secondary"
      = f.text_field field, class: "input input-sm input-bordered"

  - %i[kith house bannerhouse seeming rank location position].each do |field|
    .form-control
      = f.label field, class: "label label-text text-secondary"
      = f.text_field field, list: field, class: "input input-sm input-bordered"
      %datalist{id: field}
        = options_for_select(options_for_datalist(field))

  .form-control.mt-3
    = f.label :description, class: "label label-text text-secondary"
    = f.rich_text_area :description
  .form-control.mt-3
    = f.label :notes, class: "label label-text text-secondary"
    = f.rich_text_area :notes

  .card-actions.mt-6.flex-row-reverse
    = f.submit "Save", class: "btn btn-sm btn-secondary"

    - case local_assigns[:action]
    - when :new
      = link_to "Cancel", root_path, class: "btn btn-sm btn-primary"
    - when :edit
      = link_to "Cancel", root_path, class: "btn btn-sm btn-primary"
      = link_to "Delete", @character, { method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-error" }

app/views/characters/edit.html.haml
.card.bg-base-300.shadow-xl.mx-auto.w-full
  .card-body
    = render "form", { action: :edit }

app/views/characters/index.html.haml
.overflow-x-auto
  %table.w-full.mb-4.table.table-sm.xl:table-md.table-zebra.xl:mb-6
    %thead.uppercase
      %tr
        %th Player
        %th Fae Name
        %th Mortal Name
        %th Kith
        %th Seeming
        %th Rank
        %th Location
        %th Position
        %th= # Details
        %th= # Edit
    %tbody
      - @characters.each do |character|
        %tr.hover
          %td= character.player
          %td= character.fae_name
          %td= character.mortal_name
          %td= character.kith
          %td= character.seeming
          %td= character.rank
          %td= character.location
          %td= character.position
          %td= link_to "Details", character, class: "btn btn-sm btn-primary"
          %td= link_to "Edit", edit_character_path(character), class: "btn btn-sm btn-secondary"

.flex.flex-none.flex-col.gap-4.md:gap-0.md:flex-row.md:flex-row-reverse.md:justify-between
  %div
    = link_to "Add a New Character", new_character_path, class: "btn btn-sm xl:btn-md btn-accent"
  = paginate @characters

app/views/characters/new.html.haml
.card.bg-base-300.shadow-xl.mx-auto.w-full
  .card-body
    = render "form", { action: :new }

app/views/characters/show.html.haml
.card.bg-base-300.shadow-xl.max-w-prose.mx-auto
  .card-body
    - %i[player fae_name mortal_name kith house bannerhouse seeming rank location position].each do |f|
      - if @character.send(f).present?
        %p
          %strong= "#{f.to_s.titlecase}:"
          = @character.send(f)

    - %i[description notes].each do |f|
      - if @character.send(f).body.present?
        .mt-3.w-full.border-b.border-current
          %strong= "#{f.to_s.titlecase}"
        .prose
          = @character.send(f)

    .card-actions.justify-end.mt-3
      = link_to "Edit", edit_character_path(@character), class: "btn btn-sm btn-secondary"

app/views/characters/vue.html.haml
- # nothing

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "NOODP", :name => "ROBOTS"}/
    %meta{:content => "initial-scale=1", :name => "viewport"}/
    %title
      #{content_for(:title)} - #{application_title}
    = render "stylesheet"
    = csrf_meta_tags
    = csp_meta_tag if defined?(csp_meta_tag)

  %body
    = render "icons"

    .app-container
      = render "navigation"

      %main.main-content{:role => "main"}
        = render "flashes"
        = yield

    = render "javascript"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}
    %title= @title || 'Dramatis Personae'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = vite_javascript_tag 'application'
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
    = render(partial: 'shared/favicon')

  %body
    .w-full.mx-auto.lg:w-full.lg:container{class: "md:w-11/12"}
      = render(partial: 'shared/navbar')
      = render(partial: 'shared/alerts')
      = yield

app/views/layouts/vue.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}
    %title= @title || 'Dramatis Personae'
    = csrf_meta_tags
    = csp_meta_tag
    = vite_client_tag
    = vite_javascript_tag 'main'
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
    = render(partial: 'shared/favicon')

  %body
    #app{data: { flash: { notice: notice,
                          alert: alert },
                 user: { email: (current_account.email if rodauth.logged_in?),
                         admin: ("true" if (rodauth.logged_in? && current_account.admin?)) },
                 query: (params[:q] if params.key?(:q)) }}
      = yield

app/views/rodauth/_login_form.html.haml
= form_with url: rodauth.login_path, method: :post, data: { turbo: false }, class: "flex flex-col gap-3" do |form|
  - if rodauth.skip_login_field_on_login?
    .form-control
      = form.label "login", rodauth.login_label, class: "label label-text"
      = form.email_field rodauth.login_param, value: params[rodauth.login_param], id: "login", readonly: true,
        class: "input input-bordered"
  - else
    .form-control
      = form.label "login", rodauth.login_label, class: "label label-text"
      = form.email_field rodauth.login_param, value: params[rodauth.login_param], placeholder: rodauth.login_label.capitalize,
        id: "login", autocomplete: rodauth.login_field_autocomplete_value, required: true,
        class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.login_param)}",
        aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param))
      - if rodauth.field_error(rodauth.login_param)
        %label.label
          %span.label-text-alt.text-error= rodauth.field_error(rodauth.login_param)

  - unless rodauth.skip_password_field_on_login?
    .form-control
      = form.label "password", rodauth.password_label, class: "label label-text"
      = form.password_field rodauth.password_param, value: "", placeholder: rodauth.password_label.capitalize,
        id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true,
        class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.password_param)}",
        aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param))
      - if rodauth.field_error(rodauth.password_param)
        %label.label
          %span.label-text-alt.text-error= rodauth.field_error(rodauth.password_param)

  .form-control.pt-6
    = form.submit rodauth.login_button, class: "btn"

app/views/rodauth/_login_form_footer.html.haml
- unless rodauth.login_form_footer_links.empty?
  %ul.pt-3.flex.flex-col.gap-2
    - rodauth.login_form_footer_links.sort.each do |_, link, text|
      - unless link == "/#{rodauth.verify_account_resend_route}"
        %li= link_to text, link, class: "link-hover"

app/views/rodauth/change_password.html.haml
.flex.flex-col.gap-3
  %h1.text-2xl
    Change Your Password

  = form_with url: rodauth.change_password_path, method: :post, data: { turbo: false }, class: "flex flex-col gap-3" do |form|
    - if rodauth.change_password_requires_password?
      .form-control
        = form.label "password", rodauth.password_label, class: "label label-text"
        = form.password_field rodauth.password_param, value: "", placeholder: rodauth.password_label.capitalize,
          id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true,
          class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.password_param)}",
          aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param))
        - if rodauth.field_error(rodauth.password_param)
          %label.label
            %span.label-text-alt.text-error= rodauth.field_error(rodauth.password_param)

    .form-control
      = form.label "new-password", rodauth.new_password_label, class: "label label-text"
      = form.password_field rodauth.new_password_param, value: "", placeholder: rodauth.new_password_label.capitalize,
        id: "new-password", autocomplete: "new-password", required: true,
        class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.new_password_param)}",
        aria: ({ invalid: true, describedby: "new-password_error_message" } if rodauth.field_error(rodauth.new_password_param))
      - if rodauth.field_error(rodauth.new_password_param)
        %label.label
          %span.label-text-alt.text-error= rodauth.field_error(rodauth.new_password_param)

    - if rodauth.require_password_confirmation?
      .form-control
        = form.label "password-confirm", rodauth.password_confirm_label, class: "label label-text"
        = form.password_field rodauth.password_confirm_param, value: "", placeholder: rodauth.password_confirm_label.capitalize,
          id: "password-confirm", autocomplete: "new-password", required: true,
          class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.password_confirm_param)}",
          aria: ({ invalid: true, describedby: "password-confirm_error_message" } if rodauth.field_error(rodauth.password_confirm_param))
        - if rodauth.field_error(rodauth.password_confirm_param)
          %label.label
            %span.label-text-alt.text-error= rodauth.field_error(rodauth.password_confirm_param)

    .form-control.pt-6
      = form.submit rodauth.change_password_button, class: "btn"

app/views/rodauth/create_account.html.haml
.flex.flex-col.gap-3
  %h1.text-2xl
    Create an Account

  = form_with url: rodauth.create_account_path, method: :post, data: { turbo: false }, class: "flex flex-col gap-3" do |form|
    .form-control
      = form.label "login", rodauth.login_label, class: "label label-text"
      = form.email_field rodauth.login_param, value: params[rodauth.login_param], placeholder: rodauth.login_label.capitalize,
        id: "login", autocomplete: "email", required: true,
        class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.login_param)}",
        aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param))
      - if rodauth.field_error(rodauth.login_param)
        %label.label
          %span.label-text-alt.text-error= rodauth.field_error(rodauth.login_param)

    - if rodauth.require_login_confirmation?
      .form-control
        = form.label "login-confirm", rodauth.login_confirm_label, class: "label label-text"
        = form.email_field rodauth.login_confirm_param, value: params[rodauth.login_confirm_param], placeholder: rodauth.login_confirm_label.capitalize,
          id: "login-confirm", autocomplete: "email", required: true,
          class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.login_confirm_param)}",
          aria: ({ invalid: true, describedby: "login-confirm_error_message" } if rodauth.field_error(rodauth.login_confirm_param))
        - if rodauth.field_error(rodauth.login_confirm_param)
          %label.label
            %span.label-text-alt.text-error= rodauth.field_error(rodauth.login_confirm_param)

    - if rodauth.create_account_set_password?
      .form-control
        = form.label "password", rodauth.password_label, class: "label label-text"
        = form.password_field rodauth.password_param, value: "", placeholder: rodauth.password_label.capitalize,
          id: "password", autocomplete: rodauth.password_field_autocomplete_value, required: true,
          class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.password_param)}",
          aria: ({ invalid: true, describedby: "password_error_message" } if rodauth.field_error(rodauth.password_param))
        - if rodauth.field_error(rodauth.password_param)
          %label.label
            %span.label-text-alt.text-error= rodauth.field_error(rodauth.password_param)

      - if rodauth.require_password_confirmation?
        .form-control
          = form.label "password-confirm", rodauth.password_confirm_label, class: "label label-text"
          = form.password_field rodauth.password_confirm_param, value: "", placeholder: rodauth.password_confirm_label.capitalize,
            id: "password-confirm", autocomplete: "new-password", required: true,
            class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.password_confirm_param)}",
            aria: ({ invalid: true, describedby: "password-confirm_error_message" } if rodauth.field_error(rodauth.password_confirm_param))
          - if rodauth.field_error(rodauth.password_confirm_param)
            %label.label
              %span.label-text-alt.text-error= rodauth.field_error(rodauth.password_confirm_param)

    .form-control.pt-6
      = form.submit rodauth.create_account_button, class: "btn"

app/views/rodauth/login.html.haml
.flex.flex-col.gap-3
  %h1.text-2xl
    Sign In

  = render "login_form"

  .pt-2
    != rodauth.login_form_footer

app/views/rodauth/logout.html.haml
.flex.flex-col.gap-3
  %h1.text-2xl
    Sign Out

  = form_with url: rodauth.logout_path, method: :post, data: { turbo: false }, class: "flex flex-col gap-0" do |form|
    - if rodauth.features.include?(:active_sessions)
      .form-control
        = form.label "global-logout", class: "label cursor-pointer justify-start gap-3" do
          = content_tag :span, rodauth.global_logout_label
          = form.check_box rodauth.global_logout_param, id: "global-logout", class: "toggle", include_hidden: false

    .form-control.pt-6
      = form.submit rodauth.logout_button, class: "btn"

app/views/rodauth/reset_password_request.html.haml
.flex.flex-col.gap-3
  %h1.text-2xl
    Request Password Reset

  - if rodauth.reset_password_explanatory_text
    %p.pt-6
      != rodauth.reset_password_explanatory_text

  = form_with url: rodauth.reset_password_request_path, method: :post, data: { turbo: false }, class: "flex flex-col gap-3" do |form|
    - if params[rodauth.login_param] && !rodauth.field_error(rodauth.login_param)
      = form.hidden_field rodauth.login_param, value: params[rodauth.login_param]
    - else
      .form-control
        = form.label "login", rodauth.login_label, class: "label label-text"
        = form.email_field rodauth.login_param, value: params[rodauth.login_param], placeholder: rodauth.login_label.capitalize,
          id: "login", autocomplete: "email", required: true,
          class: "input input-bordered #{"input-error" if rodauth.field_error(rodauth.login_param)}",
          aria: ({ invalid: true, describedby: "login_error_message" } if rodauth.field_error(rodauth.login_param))
        - if rodauth.field_error(rodauth.login_param)
          %label.label
            %span.label-text-alt.text-error= rodauth.field_error(rodauth.login_param)

    .form-control.pt-6
      = form.submit rodauth.reset_password_request_button, class: "btn"

app/views/shared/_navbar.html.haml
.navbar.bg-primary.text-primary-content.mb-4.lg:mb-6
  -# hamburger menu
  .lg:hidden
    %details.dropdown
      %summary.btn.btn-ghost.normal-case
        %i.fas.fa-bars
      %ul.dropdown-content.menu.mt-3.p-2.shadow.bg-primary.rounded-box.z-10.whitespace-nowrap

        %li
          %a{href: root_path}
            Home
        %li
          = form_with(url: search_path, method: :get) do |f|
            .join.gap-0
              = f.text_field(:q, { placeholder: "Search", value: params[:q], class: "input input-sm w-40 rounded-l join-item text-base-content" })
              %button.btn.btn-sm.btn-neutral.rounded-r.join-item{type: "submit"}
                %i.fas.fa-search
        %li
          %a{href: "https://rae.evilpaws.org/", rel: "nofollow", data: { confirm: "Ready to leave?" }}
            rae.evilpaws.org
            %i.fas.fa-external-link-alt

  %div
    %span.btn.btn-ghost.normal-case.text-lg
      %a.whitespace-nowrap{href: root_path}
        %i.fas.fa-masks-theater
        Dramatis Personae

  .flex.grow.justify-end
    .hidden.lg:flex.lg:pr-4
      = form_with(url: search_path, method: :get) do |f|
        .join.gap-0
          = f.text_field(:q, { placeholder: "Search", value: params[:q], class: "input input-sm w-40 lg:w-48 rounded-l join-item text-base-content" })
          %button.btn.btn-sm.btn-neutral.rounded-r.join-item{type: "submit"}
            %i.fas.fa-search

    %div.hidden.lg:flex
      %a.btn.btn-ghost.normal-case{href: "https://rae.evilpaws.org/", rel: "nofollow", data: { confirm: "Ready to leave?" }}
        %span.text-primary-content.lg:hidden.xl:inline
          rae.evilpaws.org
        %i.fas.fa-external-link-alt

    %div
      = render(partial: 'shared/user_menu')